const education = [
  {
    title: 'MS in Computer Science and Engineering',
    location: 'University of Washington',
    startDate: 'sep 2024',
    endDate: 'present',
    skills: [
      'graphics',
      'systems for machine learning',
      'digital design',
      'computer architecture',
    ],
  },
  {
    title: 'BS in Computer Science',
    location: 'University of Washington',
    startDate: 'sep 2020',
    endDate: 'jun 2024',
    skills: [
      'compilers',
      'operating systems',
      'distributed systems',
      'web browser engineering',
      'programming languages',
      'database internals',
      'data center systems',
      'computer security',
      'computer networks',
      'graphics',
      'artificial intelligence',
      'machine learning',
      'deep learning',
      'natural language processing',
      'computer vision',
      'autonomous robotics',
      'algorithms',
      'complexity',
      'quantum computation',
    ],
  },
  {
    title: 'BA in Mathematics',
    location: 'University of Washington',
    startDate: 'sep 2020',
    endDate: 'jun 2024',
    skills: [
      'probability',
      'advanced linear algebra',
      'real analysis',
      'complex analysis',
      'ring theory',
      'group theory',
      'field theory',
      'combinatorial theory',
      'linear optimization',
      'topology',
      'differential geometry',
    ],
  },
]

export default education
